name: test variables

on:
  workflow_dispatch

env:
  workflow_var: "work flow variable"

jobs:
  job1:
    runs-on: ubuntu-latest
    env:
      job_var: "job variable"
    steps:
      - name: "print variables"
        run: echo "workflow level variable=$workflow_var; job level varaible= $job_var ; variable in this step=$step_var"
        env:
          step_var: "step variable"
